name: $(ver)$(Rev:.r)
variables:
  ver: 0.2
  version: $(Build.BuildNumber) # Nuget package version
  nugetVersion: 4.9.2
  dotNetSdkVersion: 2.2.101
  reportGenerator_Version: 4.0.4
  buildConfiguration: "Release"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

trigger:
- master

pr:
- master

pool:
  name: "Hosted VS2017"

steps:
- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: sonarcloud
    organization: 'jabbera-github'
    projectKey: 'jabbera_aspnetcore-testing-role-handler'
    projectName: AspNetCore.Testing.Authentication.ClaimInjector
    projectVersion: '$(ver)'
    extraProperties: |
     sonar.cs.opencover.reportsPaths="$(Build.SourcesDirectory)\coverage\.opencover.xml"

- task: NuGetToolInstaller@0
  displayName: "Install NuGet Client"
  inputs:
    versionSpec: $(nugetVersion)

- task: DotNetCoreInstaller@0
  displayName: "Install .NET Core SDK"
  inputs:
    packageType: 'sdk'
    version: $(dotNetSdkVersion)

- task: DotNetCoreCLI@2
  displayName: "Restore"
  inputs:
    command: 'restore'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: --configuration $(buildConfiguration) --no-restore -p:Version=$(Build.BuildNumber)

- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'test'
    projects: '**/*.sln'
    arguments: --configuration $(buildConfiguration) --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=$(Build.SourcesDirectory)\Coverage\ /p:Exclude="[AspNetCore.Testing.Authentication.ClaimInjector.Site]*"

- script: >-
    dotnet tool install dotnet-reportgenerator-globaltool 
    --global 
    --version $(reportGenerator_Version)
  displayName: "Install code coverage report generator tool"

- script: >-
    reportgenerator 
    "-reports:$(Build.SourcesDirectory)\Coverage\*.xml" 
    "-targetdir:$(Build.SourcesDirectory)\Coverage\Html" 
    "-reporttypes:Cobertura;HtmlInline_AzurePipelines;Badges"
  displayName: Generate code coverage report

- task: DotNetCoreCLI@2
  displayName: "Pack"
  inputs:
    command: 'pack'
    configuration: 'release'
    packagesToPack: '**/AspNetCore.Testing.Authentication.ClaimInjector.csproj'
    nobuild: true

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: $(Build.SourcesDirectory)\coverage\html\Cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)\coverage\html

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'packages' 
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))